# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: AxisIPCamera"
$Body = @'
{
  "Name": "Axis IP Camera",
  "ShortName": "AxisIPCamera",
  "Capability": "AxisIPCamera",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "PowerShell": false,
  "CustomAliasAllowed": "Required",
  "PrivateKeyAllowed": "Forbidden",
  "SupportedOperations": {
    "Add": true,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "Description": "Enter the username of the configured \"service\" user on the camera"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "Description": "Enter the password of the configured \"service\" user on the camera"
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Select True or False depending on if SSL (HTTPS) should be used to communicate with the camera. This should always be \"True\""
    }
  ],
  "EntryParameters": [
    {
      "Name": "CertUsage",
      "DisplayName": "Certificate Usage",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": false,
        "OnReenrollment": true
      },
      "Options": "HTTPS,IEEE802.X,MQTT,Trust,Other",
      "Description": "The Certificate Usage to assign to the cert after enrollment. Can be left 'Other' to be assigned later."
    }
  ],
  "StorePathType": "",
  "StorePathValue": "",
  "JobProperties": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

